[versions]
# libraries
opentest4j = "1.3.0"
scala3 = "3.8.1"
munit = "1.2.3"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
qodana = "2025.3.1"

[libraries]
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
scala3-library = { group = "org.scala-lang", name = "scala3-library_3", version.ref = "scala3" }
scala-munit = { group = "org.scalameta", name = "munit_3", version.ref = "munit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
